name: Linux

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  Coverage:
    uses: ./.github/workflows/change-coverage.yml
    with:
      os: "ubuntu-latest"
      workpath: "/home/runner/work/doorstop/doorstop"
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  Test:
    uses: ./.github/workflows/execute-tests.yml
    with:
      os: "ubuntu-latest"
      workpath: "/home/runner/work/doorstop/doorstop"
